# Generated by Django 5.2.5 on 2025-12-08 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('India', 'India'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia')], default='India', max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('area_street', models.CharField(max_length=255, verbose_name='Area, Street, Sector, Village')),
                ('flat_house', models.CharField(max_length=255, verbose_name='Flat, House no., Building, Company, Apartment')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi'), ('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('address_type', models.CharField(choices=[('Home', '🏠 Home'), ('Work', '🏢 Work'), ('Other', '📍 Other')], default='Home', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
