# Generated by Django 5.2.5 on 2026-01-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_product',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
    ]
