# Generated by Django 5.2.5 on 2026-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_applicable_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='usage_per_user',
        ),
    ]
