# Generated by Django 5.2.5 on 2025-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('position', models.CharField(choices=[('main', 'Main Banner'), ('secondary', 'Secondary Banner'), ('promotional', 'Promotional Banner')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
