# Generated by Django 5.2.5 on 2026-02-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description',
        ),
    ]
