# Generated by Django 5.2.5 on 2025-08-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_customuser_created_at_alter_customuser_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
    ]
