# Generated by Django 5.2.5 on 2025-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_remove_customuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
