# Generated by Django 5.2.5 on 2025-08-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
