# Generated by Django 5.2.5 on 2025-11-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancellation_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('product_damaged', 'Product Damaged'), ('wrong_product', 'Wrong Product Delivered'), ('defective', 'Defective/Not Working'), ('quality_issue', 'Quality Not as Expected'), ('size_issue', 'Size/Fit Issue'), ('changed_mind', 'Changed My Mind'), ('better_price', 'Found Better Price'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='orders.order')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
