# Generated by Django 5.2.5 on 2025-08-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
